<?php require_once APP . DS . 'views' . DS . 'layouts' . DS . 'header.php'; ?>

<!-- Slim Hero -->
<?php require_once APP . DS . 'views' . DS . 'partials' . DS . 'tool-hero.php'; ?>

<!-- Tool Interface -->
<main class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 -mt-2 relative z-10 mb-16" id="tool-interface">
    <div class="bg-white rounded-2xl shadow-xl shadow-gray-200/50 border border-gray-100 p-6 sm:p-10" style="overflow: visible;">
        <!-- Custom Tool Interface Extracted from Original File -->
        <div class="pro-app-main-full animate-fade-up">

<div class="pro-card">
    
    
    <div id="eifp-drop-zone" style="margin-bottom:2rem;"></div>
    
    <div id="eifp-controls" style="display:none;margin-bottom:2rem;">
        <div class="d-flex justify-content-between align-items-center bg-light p-3 border rounded-3 text-center d-block">
            <button onclick="extractNativeImages()" class="btn btn-primary px-5 fw-bold btn-lg shadow-sm">Extract Graphical Assets <i class="fa-solid fa-search-plus ms-2"></i></button>
        </div>
    </div>
    
    <div id="eifp-status" class="text-center text-primary" style="display:none;padding:1rem;"></div>
    <div id="eifp-results" class="row g-3" style="margin-top:2rem;"></div>
</div>

<article class="tool-seo-article container mt-5 border-top pt-4">
    <header>
        <h2 class="fs-3 fw-bold mb-3">What is the Extract Images From PDF Tool?</h2>
        <p>The Extract Images From PDF tool is a forensic digital utility designed to peer into the low-level object architecture of a PDF file and isolate raw embedded raster images. Unlike standard "PDF to Image" converters that render an entire textual layout into a massive photograph, this extractor hunts specifically for native `<canvas>` objects, inserted JPEGs, and PNG assets that were originally placed inside the document by the author.</canvas></p>
        <p>This surgical extraction is critical for marketers salvaging high-resolution logos from corporate brochures, photographers recovering original portfolios, or web developers stripping pristine graphical assets from design specification PDFs generated by Illustrator without compromising the asset's original resolution payload.</p>
    </header>

    <section class="mt-4">
        <div class="pro-tip-box bg-primary-light p-4 rounded-3 shadow-sm" style="background:#f8fafc; border-left: 4px solid var(--primary);">
            <h3 class="fs-5 fw-bold mb-2"><i class="fa-solid fa-lightbulb text-warning me-2"></i> How to Use This Tool Like a Pro <span class="badge" style="background:linear-gradient(135deg,#7c3aed,#a855f7);color:#fff;">PRO</span></h3>
            <ul class="mb-0 text-muted">
                <li class="mb-1"><strong>Forensic Scanning:</strong> Simply drop your PDF into the zone. Our script recursively parses through XObject operators across every page layer to find base raster sources.</li>
                <li class="mb-1"><strong>Hidden Assets:</strong> Be aware that this tool may uncover tiny 1x1 pixel tracking images, hidden watermark layers, or icon sprites that are invisible to standard PDF readers but recorded in the object graph.</li>
            </ul>
        </div>
    </section>

    <section class="mt-4">
        <h3 class="fs-4 fw-bold mb-3">Key Features &amp; Premium Benefits</h3>
        <div class="row g-4">
            <div class="col-md-6">
                <div class="d-flex align-items-start bg-white p-3 rounded-3 shadow-sm border">
                    <i class="fa-solid fa-magnifying-glass text-success fs-3 me-3 mt-1"></i>
                    <div><h4 class="fs-6 fw-bold mb-1">XObject Parsing</h4><p class="text-muted small mb-0">Analyzes PaintImageXObject operators directly via Mozilla's API.</p></div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="d-flex align-items-start bg-white p-3 rounded-3 shadow-sm border">
                    <i class="fa-solid fa-download text-primary fs-3 me-3 mt-1"></i>
                    <div><h4 class="fs-6 fw-bold mb-1">Original Quality</h4><p class="text-muted small mb-0">Retrieves the asset exactly as it was compressed into the PDF.</p></div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="d-flex align-items-start bg-white p-3 rounded-3 shadow-sm border">
                    <i class="fa-solid fa-crop text-warning fs-3 me-3 mt-1"></i>
                    <div><h4 class="fs-6 fw-bold mb-1">No Text Cross-contamination</h4><p class="text-muted small mb-0">Unlike page-renders, extracted images do not include overlay text.</p></div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="d-flex align-items-start bg-white p-3 rounded-3 shadow-sm border">
                    <i class="fa-solid fa-user-shield text-info fs-3 me-3 mt-1"></i>
                    <div><h4 class="fs-6 fw-bold mb-1">Client-Side Autonomy</h4><p class="text-muted small mb-0">Heavily optimized memory workers run solely in your machine RAM.</p></div>
                </div>
            </div>
        </div>
    </section>

    <section class="mt-5 mb-5">
        <h3 class="fs-4 fw-bold mb-3">Frequently Asked Questions (FAQs)</h3>
        <div class="accordion" id="toolFaqAccordion">
            <div class="accordion-item">
                <h2 class="accordion-header"><button class="accordion-button collapsed fw-bold" type="button" data-bs-toggle="collapse" data-bs-target="#faq1">Why did it extract a logo in 5 different pieces?</button></h2>
                <div id="faq1" class="accordion-collapse collapse" data-bs-parent="#toolFaqAccordion"><div class="accordion-body text-muted">Because of how PDF generators operate, what looks like a single graphic is often sliced into vector sub-components to optimize loading and layering. We extract exactly what the structural graph holds.</div></div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header"><button class="accordion-button collapsed fw-bold" type="button" data-bs-toggle="collapse" data-bs-target="#faq2">Can it extract vector SVG charts?</button></h2>
                <div id="faq2" class="accordion-collapse collapse" data-bs-parent="#toolFaqAccordion"><div class="accordion-body text-muted">No. Vector paths are mathematical directions drawn onto the PDF canvas, not embedded image objects. This tool only targets raster payloads (e.g. photos embedded inside the PDF).</div></div>
            </div>
        </div>
    </section>
</article>
</div>
    </div>
</main>

<!-- Content + Sidebar (SEO, FAQ) -->
<section class="py-16 px-4 sm:px-6 lg:px-8 border-t border-gray-200 bg-white">
    <div class="max-w-3xl mx-auto">
        <article class="prose prose-blue prose-lg max-w-none text-gray-600 mb-12" id="seo-article-content">
            
            <!-- Features Cards -->
            <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12 not-prose mt-8 mb-8">
                <div class="bg-gray-50 border border-gray-200 rounded-xl p-6 text-center shadow-sm">
                    <div class="w-12 h-12 bg-white text-primary rounded-full flex items-center justify-center text-xl mx-auto mb-4 border border-gray-100"><i class="fa-solid fa-bolt"></i></div>
                    <h4 class="font-bold text-gray-900 mb-2">Lightning Fast</h4>
                    <p class="text-sm text-gray-500">Get your results instantly without waiting or reloading.</p>
                </div>
                <div class="bg-gray-50 border border-gray-200 rounded-xl p-6 text-center shadow-sm">
                    <div class="w-12 h-12 bg-white text-primary rounded-full flex items-center justify-center text-xl mx-auto mb-4 border border-gray-100"><i class="fa-solid fa-shield-halved"></i></div>
                    <h4 class="font-bold text-gray-900 mb-2">100% Secure</h4>
                    <p class="text-sm text-gray-500">All data processing happens securely in your own browser.</p>
                </div>
                <div class="bg-gray-50 border border-gray-200 rounded-xl p-6 text-center shadow-sm">
                    <div class="w-12 h-12 bg-white text-primary rounded-full flex items-center justify-center text-xl mx-auto mb-4 border border-gray-100"><i class="fa-solid fa-wand-magic-sparkles"></i></div>
                    <h4 class="font-bold text-gray-900 mb-2">Easy to Use</h4>
                    <p class="text-sm text-gray-500">No complex settings, just drop your data and execute.</p>
                </div>
            </div>
        </article>
    </div>
</section>

<!-- Suggested Tools Strip -->
<?php require_once APP . DS . 'views' . DS . 'partials' . DS . 'tool-suggested.php'; ?>

<!-- Popular Tools Section -->
<section class="bg-white py-16 px-4 sm:px-6 lg:px-8 border-t border-gray-100">
    <div class="max-w-7xl mx-auto">
        <div class="flex items-center justify-between mb-8">
            <h2 class="text-2xl font-bold text-gray-900 tracking-tight">Most Popular Tools</h2>
            <a href="<?php echo URL_ROOT; ?>" class="text-sm font-medium text-primary hover:text-primary-hover transition-colors">See All &rarr;</a>
        </div>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <?php 
            $allToolsRegistry = require CONFIG . DS . 'tools_registry.php';
            $popularTools = array_slice($allToolsRegistry, 0, 4, true); 
            foreach ($popularTools as $pSlug => $pTool): 
            ?>
            <a href="<?php echo URL_ROOT; ?>/<?php echo $pSlug; ?>" class="group bg-gray-50 border border-gray-200 rounded-xl p-5 flex gap-4 items-start hover:border-primary/50 hover:shadow-lg hover:shadow-primary/5 transition-all duration-200">
                <div class="flex-shrink-0 w-12 h-12 bg-white text-primary rounded-lg flex items-center justify-center text-xl group-hover:bg-primary group-hover:text-white transition-colors duration-200 shadow-sm border border-gray-100">
                    <?php echo render_tool_icon($pTool['icon']); ?>
                </div>
                <div class="flex-grow min-w-0">
                    <h3 class="text-base font-semibold text-gray-900 truncate mb-1 group-hover:text-primary transition-colors"><?php echo htmlspecialchars($pTool['title']); ?></h3>
                    <p class="text-xs text-gray-500 line-clamp-2 leading-relaxed"><?php echo htmlspecialchars($pTool['desc']); ?></p>
                </div>
            </a>
            <?php endforeach; ?>
        </div>
    </div>
</section>



<script src="<?php echo URL_ROOT; ?>/assets/js/pdf-developer-tools.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js"></script>
<script>
pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';

let activeEifpFile = null;
PdfDevPro.buildDropZone('eifp-drop-zone', {accept: 'application/pdf', title: 'PDF document', icon: '🔍', onFiles: files => {
    activeEifpFile = files[0];
    document.getElementById('eifp-controls').style.display = 'block';
}});

async function extractNativeImages() {
    if(!activeEifpFile) return;
    const status = document.getElementById('eifp-status');
    const resDiv = document.getElementById('eifp-results');
    status.style.display = 'block';
    resDiv.innerHTML = '';
    
    try {
        status.textContent = 'Forensically scanning PDF operators...';
        const fileBuffer = await PdfDevPro.readFileAsArrayBuffer(activeEifpFile);
        const pdf = await pdfjsLib.getDocument({ data: fileBuffer }).promise;
        const total = pdf.numPages;
        
        let imgCount = 0;
        
        for(let i=1; i<=total; i++) {
            status.textContent = `Scanning Page ${i} / ${total}...`;
            const page = await pdf.getPage(i);
            const opList = await page.getOperatorList();
            
            // Loop through operators looking for images
            for(let j=0; j < opList.fnArray.length; j++) {
                // In pdf.js paintImageXObject is code 85 or handled via specific fns
                if (opList.fnArray[j] === pdfjsLib.OPS.paintImageXObject || opList.fnArray[j] === pdfjsLib.OPS.paintJpegXObject) {
                    const objId = opList.argsArray[j][0];
                    try {
                        const img = await page.objs.get(objId);
                        if (img && img.data && img.width && img.height) {
                            imgCount++;
                            const canvas = document.createElement('canvas');
                            canvas.width = img.width;
                            canvas.height = img.height;
                            const ctx = canvas.getContext('2d');
                            // Create ImageData
                            const imgData = new ImageData(new Uint8ClampedArray(img.data), img.width, img.height);
                            ctx.putImageData(imgData, 0, 0);
                            
                            const dataUrl = canvas.toDataURL('image/png');
                            resDiv.innerHTML += `
                            <div class="col-md-3 text-center">
                                <div class="border rounded-3 p-2 bg-white shadow-sm h-100 d-flex flex-column align-items-center justify-content-between">
                                    <div style="background:var(--bg-body); padding:10px; border-radius:8px; width:100%; display:flex; justify-content:center; align-items:center; min-height:120px;">
                                        <img src="${dataUrl}" style="max-width:100%; max-height:100px;">
                                    </div>
                                    <div class="w-100 mt-2">
                                        <div class="text-muted small fw-bold mb-1">Pg ${i} · ${img.width}x${img.height}</div>
                                        <a href="${dataUrl}" download="extracted_asset_${imgCount}.png" class="btn btn-sm btn-outline-primary w-100">Save Asset</a>
                                    </div>
                                </div>
                            </div>`;
                        }
                    } catch(ex) { console.log('Failed to parse object: ' + objId); }
                }
            }
        }
        
        if (imgCount === 0) {
            status.innerHTML = `<span class="text-warning">⚠️ No graphical raster assets found embedded in this document.</span>`;
        } else {
            status.innerHTML = `<span class="text-success">✅ Successfully isolated ${imgCount} native raster images!</span>`;
            PdfDevPro.toast(`Found ${imgCount} images!`);
        }
        
    } catch(e) {
        status.innerHTML = `<span class="text-danger">Error Context: ${e.message}</span>`;
    }
}
</script>


<?php require_once APP . DS . 'views' . DS . 'layouts' . DS . 'footer.php'; ?>