<?php require_once APP . DS . 'views' . DS . 'layouts' . DS . 'header.php'; ?>

<!-- Slim Hero -->
<?php require_once APP . DS . 'views' . DS . 'partials' . DS . 'tool-hero.php'; ?>

<!-- Tool Interface -->
<main class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 -mt-2 relative z-10 mb-16" id="tool-interface">
    <div class="bg-white rounded-2xl shadow-xl shadow-gray-200/50 border border-gray-100 p-6 sm:p-10">
        <!-- Custom Tool Interface Extracted from Original File -->
        
            
            <div class="row gx-4 mb-4">
                <!-- Left Text -->
                <div class="col-md-6 mb-4 mb-md-0">
                    <div class="d-flex justify-content-between align-items-center mb-2">
                        <h5 class="fw-bold mb-0 text-muted"><i class="fa-solid fa-file-lines me-2"></i>Original Text</h5>
                        <button class="btn btn-sm btn-light text-primary fw-bold" onclick="document.getElementById('text-left').value=''; diffCheck();">Clear</button>
                    </div>
                    <textarea id="text-left" class="form-control border-2 bg-light rounded-4 p-3 shadow-sm diff-input" rows="8" placeholder="Paste the original foundational text here..." style="font-family: var(--font-mono); font-size: 14px;"></textarea>
                </div>

                <!-- Right Text -->
                <div class="col-md-6">
                    <div class="d-flex justify-content-between align-items-center mb-2">
                        <h5 class="fw-bold mb-0 text-muted"><i class="fa-solid fa-file-signature me-2"></i>Modified Text</h5>
                        <button class="btn btn-sm btn-light text-primary fw-bold" onclick="document.getElementById('text-right').value=''; diffCheck();">Clear</button>
                    </div>
                    <textarea id="text-right" class="form-control border-2 bg-light rounded-4 p-3 shadow-sm diff-input" rows="8" placeholder="Paste the modified or updated text here..." style="font-family: var(--font-mono); font-size: 14px;"></textarea>
                </div>
            </div>

            <div class="d-flex justify-content-center mb-4">
                <button class="btn btn-primary rounded-pill px-5 shadow-sm py-2 fs-5" onclick="diffCheck()"><i class="fa-solid fa-shuffle me-2"></i>Compute Differentials</button>
            </div>

            <!-- Output Block -->
            <div id="diff-output-container" class="border-2 border rounded-4 shadow-sm overflow-hidden d-none">
                <div class="bg-light border-bottom p-3 d-flex justify-content-between align-items-center">
                    <h5 class="fw-bold mb-0 text-dark"><i class="fa-solid fa-magnifying-glass me-2 text-primary"></i>Computed Variance</h5>
                    <div class="d-flex gap-3 text-sm fw-bold">
                        <span class="text-danger"><ins class="d-inline-block rounded px-1 text-decoration-none" style="background:#fee2e2;">Deletions</ins></span>
                        <span class="text-success"><ins class="d-inline-block rounded px-1 text-decoration-none" style="background:#dcfce7;">Insertions</ins></span>
                    </div>
                </div>
                <div class="p-4 bg-white" style="font-family: var(--font-mono); font-size: 15px; line-height: 1.6; white-space: pre-wrap; word-break: break-word; max-height: 500px; overflow-y: auto;" id="diff-content">
                    <!-- HTML generated by diff-match-patch -->
                </div>
            </div>

        
    </div>
</main>

<!-- Content + Sidebar (SEO, FAQ) -->
<section class="py-16 px-4 sm:px-6 lg:px-8 border-t border-gray-200 bg-white">
    <div class="max-w-3xl mx-auto">
        <article class="prose prose-blue prose-lg max-w-none text-gray-600 mb-12">
            <h2 class="text-2xl font-bold text-gray-900 mb-4 tracking-tight">Visualizing Linguistic Deltas</h2>
                    <p class="lead">Understanding exactly what changed between two massive blocks of text or raw code is virtually impossible for the human eye. Operating identically to Git's internal version control engine, our <strong>Pro Text Diff Checker</strong> mathematically calculates the specific differences (Deltas) between two matrices to highlight exactly what was added and removed.</p>
            <!-- Features Cards -->
            <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12 not-prose mt-8 mb-8">
                <div class="bg-gray-50 border border-gray-200 rounded-xl p-6 text-center shadow-sm">
                    <div class="w-12 h-12 bg-white text-primary rounded-full flex items-center justify-center text-xl mx-auto mb-4 border border-gray-100"><i class="fa-solid fa-bolt"></i></div>
                    <h4 class="font-bold text-gray-900 mb-2">Lightning Fast</h4>
                    <p class="text-sm text-gray-500">Get your results instantly without waiting or reloading.</p>
                </div>
                <div class="bg-gray-50 border border-gray-200 rounded-xl p-6 text-center shadow-sm">
                    <div class="w-12 h-12 bg-white text-primary rounded-full flex items-center justify-center text-xl mx-auto mb-4 border border-gray-100"><i class="fa-solid fa-shield-halved"></i></div>
                    <h4 class="font-bold text-gray-900 mb-2">100% Secure</h4>
                    <p class="text-sm text-gray-500">All data processing happens securely in your own browser.</p>
                </div>
                <div class="bg-gray-50 border border-gray-200 rounded-xl p-6 text-center shadow-sm">
                    <div class="w-12 h-12 bg-white text-primary rounded-full flex items-center justify-center text-xl mx-auto mb-4 border border-gray-100"><i class="fa-solid fa-wand-magic-sparkles"></i></div>
                    <h4 class="font-bold text-gray-900 mb-2">Easy to Use</h4>
                    <p class="text-sm text-gray-500">No complex settings, just drop your data and execute.</p>
                </div>
            </div>
                    
                    <h3 class="text-xl font-bold text-gray-900 mt-5 mb-3">Powered by Diff-Match-Patch</h3>
                    <p>Under the hood, this tool integrates the incredibly robust <code>Diff-Match-Patch</code> algorithm originally engineered by Google researchers. Instead of executing simple line-by-line checks, it actively measures Levenshtein distances and semantic structural shifts, allowing it to highlight specific character edits within a single sentence, rather than just scrapping the entire paragraph.</p>

                    <h3 class="text-xl font-bold text-gray-900 mt-5 mb-3">Zero Telemetry Execution</h3>
                    <p>Proprietary source code, legal contracts, and intellectual property are highly sensitive. Unlike centralized diffing services that transmit your data arrays across the web to be processed on their servers, this engine forces the complex algorithmic comparisons to run entirely within the memory footprint of your local web browser. Your inputs remain 100% confidential and air-gapped.</p>
        </article>
    </div>
</section>

<!-- Suggested Tools Strip -->
<?php require_once APP . DS . 'views' . DS . 'partials' . DS . 'tool-suggested.php'; ?>

<!-- Popular Tools Section -->
<section class="bg-white py-16 px-4 sm:px-6 lg:px-8 border-t border-gray-100">
    <div class="max-w-7xl mx-auto">
        <div class="flex items-center justify-between mb-8">
            <h2 class="text-2xl font-bold text-gray-900 tracking-tight">Most Popular Tools</h2>
            <a href="<?php echo URL_ROOT; ?>" class="text-sm font-medium text-primary hover:text-primary-hover transition-colors">See All &rarr;</a>
        </div>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <?php 
            $allToolsRegistry = require CONFIG . DS . 'tools_registry.php';
            $popularTools = array_slice($allToolsRegistry, 0, 4, true); 
            foreach ($popularTools as $pSlug => $pTool): 
            ?>
            <a href="<?php echo URL_ROOT; ?>/<?php echo $pSlug; ?>" class="group bg-gray-50 border border-gray-200 rounded-xl p-5 flex gap-4 items-start hover:border-primary/50 hover:shadow-lg hover:shadow-primary/5 transition-all duration-200">
                <div class="flex-shrink-0 w-12 h-12 bg-white text-primary rounded-lg flex items-center justify-center text-xl group-hover:bg-primary group-hover:text-white transition-colors duration-200 shadow-sm border border-gray-100">
                    <?php echo render_tool_icon($pTool['icon']); ?>
                </div>
                <div class="flex-grow min-w-0">
                    <h3 class="text-base font-semibold text-gray-900 truncate mb-1 group-hover:text-primary transition-colors"><?php echo htmlspecialchars($pTool['title']); ?></h3>
                    <p class="text-xs text-gray-500 line-clamp-2 leading-relaxed"><?php echo htmlspecialchars($pTool['desc']); ?></p>
                </div>
            </a>
            <?php endforeach; ?>
        </div>
    </div>
</section>


<style>
.text-gradient-primary { background: linear-gradient(45deg, #059669, #0284c7); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
.diff-input:focus { border-color: #0284c7 !important; box-shadow: 0 0 0 .25rem rgba(2, 132, 199, .25) !important; }

/* Custom Styling for diff-match-patch output */
#diff-content del { background-color: #fee2e2; color: #991b1b; text-decoration: none; padding: 0 2px; border-radius: 3px; }
#diff-content ins { background-color: #dcfce7; color: #166534; text-decoration: none; padding: 0 2px; border-radius: 3px; border-bottom: 1px solid #22c55e;}
</style>

<script src="https://cdnjs.cloudflare.com/ajax/libs/diff_match_patch/20121119/diff_match_patch.js"></script>
<script>
document.addEventListener('DOMContentLoaded', () => {

    const dmp = new diff_match_patch();
    const tLeft = document.getElementById('text-left');
    const tRight = document.getElementById('text-right');
    const container = document.getElementById('diff-output-container');
    const content = document.getElementById('diff-content');

    window.diffCheck = () => {
        const text1 = tLeft.value;
        const text2 = tRight.value;

        if (!text1 && !text2) {
            container.classList.add('d-none');
            return;
        }

        container.classList.remove('d-none');

        // Allow UI to unfreeze
        setTimeout(() => {
            const diffs = dmp.diff_main(text1, text2);
            dmp.diff_cleanupSemantic(diffs); // Makes the diffs much more human readable!
            
            const htmlStream = dmp.diff_prettyHtml(diffs);
            
            // The default library uses inline styles <del style="..."> and <ins style="...">. 
            // We strip their inline colors to use our custom Bootstrap-friendly CSS defined above.
            const cleanHtml = htmlStream
                .replace(/style="background:#e6ffe6;"/g, '')
                .replace(/style="background:#ffe6e6;"/g, '');

            content.innerHTML = cleanHtml;
            
        }, 50);
    };

    // Load samples
    window.loadSamples = () => {
        tLeft.value = "The quick brown fox jumps over the lazy dog.\n\nThis tool is awesome.";
        tRight.value = "The fast brown fox jumps over the sleepy dog.\n\nThis Pro tool is truly awesome.";
        diffCheck();
    };
});
</script>


<?php require_once APP . DS . 'views' . DS . 'layouts' . DS . 'footer.php'; ?>